-- Turn off diagnostics for helm buffers
-- local bufnr = vim.api.nvim_get_current_buf()
-- vim.diagnostic.disable(bufnr)
-- vim.defer_fn(function()
--   vim.diagnostic.reset(nil, bufnr)
-- end, 1000)
vim.defer_fn(function()
  vim.cmd('LspStop yamlls')
end, 1000)
vim.defer_fn(function()
  vim.cmd('LspStart helm-ls')
end, 2000)
